### ISSUE TITLE
Running with project not working on latest version

### ISSUE THREAD

**Issue by pdetrempe** [jondeuce/MATDaemon.jl#11]
Hi there,

Since updating from [here](https://github.com/jondeuce/MATDaemon.jl/commit/ab87586482478d340c25be54d921ba8f551b33b1) to the latest version, I'm now getting a breaking error when running with 0 arguments:

```
jlcall('', ...
        'restart', true,...
        'project', matlab_wrappers_dir, ...               % activate a local Julia Project
        'setup', which('setup.jl'), ...                                      % run a setup script to load some custom Julia code        
        'modules', {'LinearAlgebra', 'MATLABGuidanceWrappers', 'StaticArrays'}, ...  % load a custom module and some modules from Base Julia
        'threads', 'auto', ... % use the default number of Julia threads
        'debug', true,...
        'server', false)
```

Output error message from the julia script here:

![image](https://github.com/jondeuce/MATDaemon.jl/assets/24377991/ecaec483-d3f6-4a0c-a409-344909c6f126)

**Comment by jondeuce** [comment]
It's a similar issue as [before](https://github.com/jondeuce/MATDaemon.jl/issues/9#issuecomment-1765447576): update your `.jlcall` environment. I added those flags in `v0.1.3`.

In general when you update `jlcall.m` you should make sure to update `MATDaemon` as well. Starting with `v0.1.3`, `MATDaemon` will warn you if there is a version mismatch between `MATDaemon` and `jlcall.m`.

**Comment by pdetrempe** [comment]
Thanks for the quick response! I removed the `.jlcall` folder entirely and got a message that it was reinstalling, however, I'm still getting the same error regarding unsupported kwargs. Any other ideas?

![image](https://github.com/jondeuce/MATDaemon.jl/assets/24377991/79f186b6-4880-427d-a0de-85f3655f3ac4)

I also confirmed that rolling back my version to `ab87586...` resulting in things working again.

![image](https://github.com/jondeuce/MATDaemon.jl/assets/24377991/de1d2f85-dd28-44a7-af0f-c3e05dba0396)

**Comment by jondeuce** [comment]
Ah okay, this is definitely my fault; I added some features to `jlcall.m` without updating the `MATDaemon` version accordingly; I'll do this now. Thanks for raising this issue. In the meantime, installing the master branch should fix the error you see: `julia --project=.jlcall -e 'using Pkg; Pkg.add(name="MATDaemon", rev="master")'`.

Also, just to clear up a possible source of confusion: the version of MATDaemon installed into the `.jlcall` workspace folder has nothing to do with the version you have installed in `~/.julia/dev`; MATDaemon manages a new separate Julia environment at `.jlcall/Project.toml`. Right now, installation in this environment simply calls `add MATDaemon`, but this is not in general guaranteed to get the latest package version, so I'll also modify `jlcall.m` to run `Pkg.update()` after installation.

**Comment by jondeuce** [comment]
Alright, looks like the new version is good to go. Easiest way to update MATDaemon is to download [`jlcall.m` v0.1.4](https://github.com/jondeuce/MATDaemon.jl/blob/v0.1.4/api/jlcall.m) and delete the `.jlcall` workspace folder and let `jlcall.m` reinstall it.

**Comment by pdetrempe** [comment]
> Alright, looks like the new version is good to go. Easiest way to update MATDaemon is to download [`jlcall.m` v0.1.4](https://github.com/jondeuce/MATDaemon.jl/blob/v0.1.4/api/jlcall.m) and delete the `.jlcall` workspace folder and let `jlcall.m` reinstall it.

This worked for me, thanks!
