### ISSUE TITLE
error getting matdaemon to call Julia 

### ISSUE THREAD

**Issue by sasandoval** [jondeuce/MATDaemon.jl#12]
I get an error when trying to run the example jlcall('sort', {rand(2,5)}, struct('dims', int64(2))) function from the readme. I have tried adding Julia to the PATH in multiple ways (along with @pdetrempe), including creating an alias and I still get a status = 127 error when using jlcall > try_run

**Comment by jondeuce** [comment]
Please include the error message. Also, you can pass the path to the Julia binary directly using the 'runtime' flag.

**Comment by sasandoval** [comment]
Hi, thanks for your reply. Here is the error that I get:

![Screenshot 2023-12-13 at 4 35 04 PM](https://github.com/jondeuce/MATDaemon.jl/assets/153779949/84b114c8-280d-4789-b2e0-76ccdabcc62d)

On your comment about passing the path to the Julia binary directly. I am not familiar with that 'runtime' flag, can you point me to a good reference to do that? 

Thank you.

**Comment by kamesy** [comment]
The runtime flag can be used to directly pass the path of the julia executable: `jlcall(..., 'runtime', '/path/to/julia')`

**Comment by sasandoval** [comment]
Thanks for the suggestion, when I tried doing that, I didn't get the error anymore but MATLAB did not get past the following:

![Screenshot 2023-12-21 at 11 51 57 AM](https://github.com/jondeuce/MATDaemon.jl/assets/153779949/2b559dc2-c364-4441-b9c8-fb90944c4ecc)

When I stopped the simulation after ~20 minutes, I got the following:

![Screenshot 2023-12-21 at 11 56 28 AM](https://github.com/jondeuce/MATDaemon.jl/assets/153779949/bdee5ed4-b80b-4205-8a12-7bcce20f13a3)
