### ISSUE TITLE
I get lots of errors if this is called by multiple Matlab processes running in parallel

### ISSUE THREAD

**Issue by salbert83** [jondeuce/MATDaemon.jl#13]
I modified 'infile' and 'outfile' so these would be unique to the calling process, but I still get lots of errors.   Am I using this module in an unintended way?

**Comment by jondeuce** [comment]
Can you post the error messages you are receiving? I haven't thought about calling `jlcall` from parallel Matlab instances, but I can't see why it wouldn't work; 'infile' and 'outfile', for example, are already given unique names with each call, so I don't think it's that.

EDIT: On second thought, it is likely that you will need to set the 'port' flag to different values on each Matlab instance, giving each instance their own separate Julia server.
