### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by matthewelmer-tamu** [jondeuce/MATDaemon.jl#15]
I'll see if doing `pkg> add MATDaemon` from Julia works, but it would be great if the readme explicitly said that this would install the necessary Matlab files and add them to Matlab's path.

**Comment by matthewelmer-tamu** [comment]
Update: Nope. That didn't seem to work. I have no idea how to get started with this. Am I missing a link to the documentation somewhere?

**Comment by jondeuce** [comment]
Download [`jlcall.m`](https://github.com/jondeuce/MATDaemon.jl/blob/v0.1.4/api/jlcall.m) and it will install `MATDaemon.jl` for you (the Julia project environment MATDaemon is installed into is placed in a folder `.jlcall` in the same folder you place `jlcall.m`).

**Comment by matthewelmer-tamu** [comment]
I will have to try this later! Feel free to close the issue -- otherwise, someone could close it with a PR that adds this guidance to the Quickstart section of the README.

**Comment by jondeuce** [comment]
[Done](https://github.com/jondeuce/MATDaemon.jl#installation) :+1:
