### ISSUE TITLE
Extra "shutdown" parameter on JLCallOptions not compatible with published version v0.1.1

### ISSUE THREAD

**Issue by akielbowicz** [jondeuce/MATDaemon.jl#5]
Hi I was trying this package out and got into an error of an `shutdown` being an unrecognized parameter.

I think that the `jlcall.m` script is out of sync with the published `MATDaemon.jl` v0.1.1

**Reproduction steps:**

1) Download [jlcall.m](https://github.com/jondeuce/MATDaemon.jl/blob/99c9092004c08cb6ccefe08508719a1d3a89a89a/api/jlcall.m) into your machine 
2) load into Matlab 
3) run the simplest command 

```matlab
>> jlcall('')
* Installing MATDaemon...
```
wait and get an error

```matlab
>> jlcall('','debug',true)
ERROR: LoadError: MethodError: no method matching MATDaemon.JLCallOptions(; shared=true, threads=24, setup="", debug=true, gc=true, workspace=".../MATDaemon.jl/api/.jlcall", outfile="/tmp/tp12710840444099472.mat", cwd="..../MATDaemon.jl", project="", infile="/tmp/tp12710840441051096.mat", f="(args...; kwargs...) -> nothing", shutdown=false, port=3000.0, nofun=false, modules=Any[], runtime="/home/.../.juliaup/bin/julia", server=true, restart=false)
Stacktrace:
 [1] kwerr at ./error.jl:163
 [2] load_options at /home/.../.julia/packages/MATDaemon/2Z92q/src/MATDaemon.jl:134
 [3] top-level scope at /home/.../.julia/packages/MATDaemon/2Z92q/api/jlcall.jl:11
 [4] include at ./client.jl:451
 [5] top-level scope at /home/...../MATDaemon.jl/api/.jlcall/tmp/0006_mat_tp12710840815091344.jl:5
 [6] eval at ./boot.jl:373

* Sending `DaemonMode.runfile` script to Julia server (status = 0):
*   /home/.../.juliaup/bin/julia --project=/home/..../MATDaemon.jl/api/.jlcall --threads=auto --startup-file=no --optimize=0 --compile=min /home/..../MATDaemon.jl/api/.jlcall/tmp/0007_mat_tp12710840821855416.jl

Error using jlcall>call_julia (line 417)
Julia call failed to produce the expected output file:
/tmp/tp12710840444099472.mat

Error in jlcall (line 245)
    varargout = call_julia(f_args, opts);
```

**Temporary fix**: install latest `MATDaemon.jl` from github 

Look  into  the folder where `jlcall.m` was downloaded, there should be a new `.jlcall` folder with the `Project.toml` file.
```shell
>julia --project='[somepath]/.jlcall'
>]
(.jlcall) pkg> add https://github.com/jondeuce/MATDaemon.jl.git
    Cloning git-repo `https://github.com/jondeuce/MATDaemon.jl.git`
    Updating git-repo `https://github.com/jondeuce/MATDaemon.jl.git`
    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
    Updating `~/...../.jlcall/Project.toml`
  [88578114] ~ MATDaemon v0.1.1 ⇒ v0.1.1 `https://github.com/jondeuce/MATDaemon.jl.git#master`
    Updating `~/...../.jlcall/Manifest.toml`
  [88578114] ~ MATDaemon v0.1.1 ⇒ v0.1.1 `https://github.com/jondeuce/MATDaemon.jl.git#master`
Precompiling project...
  1 dependency successfully precompiled in 1 seconds (22 already precompiled)
```
Restart Matlab and try again.

By the way, thanks for the package!! 
Now that I managed to make it run expect some more comments on the way.

**Comment by jondeuce** [comment]
Thanks for bringing this to my attention, I'm not sure how this error slipped by - I'll look into this right now.

Apologies for the slow reply, by the way, and thanks for your interest in the package!

**Comment by jondeuce** [comment]
Accidentally closed this before checking in; I have now [tagged a new version](https://github.com/jondeuce/MATDaemon.jl/commit/f4c0d2f492cd4cf2a0c840691588133d25123e90) which should fix your problem after `]update MATDaemon`. Please let me know if this didn't fix your issue, and of course feel free to open more issues as you come across them.
